version: '3.8'

services:
  event-store:
    image: eventstore/eventstore:22.10.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

  gradle:
    image: gradle
    depends_on:
      - event-store
    working_dir: /EternalEvent
    volumes:
      - .:/EternalEvent

volumes:
  eventstore-volume-data:
  eventstore-volume-logs: