name: CI

on:
  workflow_dispatch: ~
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-20.04
    name: "Run tests"
    steps:
      - uses: actions/checkout@v2
      -
        run: |
          make test
